### PR TITLE
Added brew cask cleanup.

### PR DESCRIPTION
**Pull request by JSafaiyeh**

### CODE REVIEW

**Comment by ZakariaRidouh** [comment]
you should also add 'brew cleanup'

**Comment by JSafaiyeh** [comment]
Yup! brew cleanup is already there.

**Comment by ZakariaRidouh** [comment]
Whoops, I meant `brew prune` 😁


-- Zakaria Ridouh






On Tue, Aug 16, 2016 at 11:47 AM -0700, "Jason Safaiyeh" <notifications@github.com> wrote:





Yup! brew cleanup is already there.

**Comment by JSafaiyeh** [comment]
Nice suggestion, just added.

**Pull request merged**
