### PR TITLE
Fix default Dropbox install directory

### PR DESCRIPTION
**Pull request by thameera**
Dropbox directory is `~/Dropbox` by default.

### CODE REVIEW

**Comment by guarinogabriel** [comment]
@thameera Thanks for the fix!

**Comment by Xoib** [comment]
Great! Just forgot to also fix the sentence at https://github.com/guarinogabriel/Mac-CLI/blob/master/mac-cli/tools/install#L56

**Comment by thameera** [comment]
Oops, sorry, missed that. I pushed a new commit fixing this to the branch, but apparently the PR isn't updated by that. Should I open a new PR?

**Comment by Xoib** [comment]
Yes, as this PR is merged it don't accept any new commit.

**Pull request merged**
