### PR TITLE
Bash completion

### PR DESCRIPTION
**Pull request by VasuCigareddy**
Bash completion for Mac-CLI

* Install script will now check for "brew bash-completion" if exists  it just copies bash_completion file from mac-cli/misc directory to brew's bash-completion directory `(brew --prefix)/etc/bash_completion.d/` as _mac_ (filename).
* If "brew bash-completion" isn't there, install script will install bash-completion `brew install bash-completion` and updates bash_profile.
* _bash_completion_ will auto generate suggestions from **COMMANDS** array in main mac script.

### CODE REVIEW

**Comment by guarinogabriel** [comment]
Hi @VasuCigareddy,

Thanks so much for your contribution. I applied your changes on the following commit:
https://github.com/guarinogabriel/Mac-CLI/commit/c490b05273f70e4b4f2c0ce5d2d40a4c71d0eb9b

However, the bash completion is not working. Can you pull the latest code and check why the bash completion is not working?

Thanks!

**Comment by guarinogabriel** [comment]
@VasuCigareddy Thanks! I look forward to your PR.

**Comment by VasuCigareddy** [comment]
@guarinogabriel I've already updated the PR with the fix: https://github.com/guarinogabriel/Mac-CLI/pull/72/commits/7e63d3f7c1105eee1c8b0bd525a6ea84c497f8f8

**Comment by guarinogabriel** [comment]
Hi @VasuCigareddy ,

I've added your fixes on this commit: https://github.com/guarinogabriel/Mac-CLI/commit/715335edd728aa8ba359fb027b3dd3eddca103f4

However, the auto-completion is not working for me yet. Is it working for you? Can you download and install the latest Mac CLI version and double check that?

`https://github.com/guarinogabriel/Mac-CLI/commit/715335edd728aa8ba359fb027b3dd3eddca103f4`

Thanks!

**Comment by VasuCigareddy** [comment]
@guarinogabriel Its working fine for me. Did you try opening *new bash session* to test it? Or try sourcing it manually on your mac `source source $(brew --prefix)/etc/bash_completion`

[Video Link ](https://drive.google.com/file/d/0B0K_P6YHFHx7M3ZoZjRfYU1zRDg/view?usp=sharing)

**Comment by guarinogabriel** [comment]
@VasuCigareddy Awesome! Thanks for your great contribution.

**Pull request closed without merging**
