### PR TITLE
DHCP Lease, DNS Cache, Uptime

### PR DESCRIPTION
**Pull request by mxeise**
added dhcp renew and dns clear

### CODE REVIEW

**Comment by guarinogabriel** [comment]
@mxeise There are no changes on the PR. Could you please double-check the PR?

**Comment by mxeise** [comment]
@guarinogabriel Sorry - the changes should be up by now.

**Comment by VasuCigareddy** [comment]
@mxeise I think you also need to update `COMMANDS` array in main *mac* script: https://github.com/guarinogabriel/Mac-CLI/blob/master/mac for the new commands to work (dhcp:renew, dns:clear and uptime).

**Comment by mxeise** [comment]
@VasuCigareddy Thanks for the hint! I added the three commands in`COMMANDS`

**Pull request merged**
